kind: Deployment
apiVersion: apps/v1
metadata:
  name: game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game
        image: asia-southeast1-docker.pkg.dev/convint-testing/velu-testing/game
        ports:
        - containerPort: 3000