apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: game
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    nodePort: 31000
  selector:
    app: game